Task -1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)

In [1]:
import pandas as pd

In [3]:
import numpy as np

In [17]:
df = pd.DataFrame([['a',19,'m','cse',8.9],['b',20,'f','cse',7.9],['c',19,'m','ece',np.nan],['d',20,'m','eee',6.7],['e',21,'m',np.nan,8.2],['f',20,'f','cse',7.8],['g',19,'m','cse',np.nan],['h',19,'f','np.nan',9.1],['i',np.nan,'f','eee',8.3],['j',19,'m','cse',8.8]])
df

   0     1  2       3    4
0  a  19.0  m     cse  8.9
1  b  20.0  f     cse  7.9
2  c  19.0  m     ece  NaN
3  d  20.0  m     eee  6.7
4  e  21.0  m     NaN  8.2
5  f  20.0  f     cse  7.8
6  g  19.0  m     cse  NaN
7  h  19.0  f  np.nan  9.1
8  i   NaN  f     eee  8.3
9  j  19.0  m     cse  8.8

In [5]:
df.columns=['name','age','gender','branch','cgpa']

In [18]:
df

   0     1  2       3    4
0  a  19.0  m     cse  8.9
1  b  20.0  f     cse  7.9
2  c  19.0  m     ece  NaN
3  d  20.0  m     eee  6.7
4  e  21.0  m     NaN  8.2
5  f  20.0  f     cse  7.8
6  g  19.0  m     cse  NaN
7  h  19.0  f  np.nan  9.1
8  i   NaN  f     eee  8.3
9  j  19.0  m     cse  8.8

In [16]:
df.shape #  checking if there are 10 oservations and 5 features

(10, 5)

Task- 2 Check the info of 'df'

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     9 non-null      float64
 2   gender  10 non-null     object
 3   branch  9 non-null      object
 4   cgpa    8 non-null      float64
dtypes: float64(2), object(3)
memory usage: 528.0+ bytes

Task 3- Check the descriptive statistics of 'df'

In [8]:
df.describe()

             age     cgpa
count   9.000000  8.00000
mean   19.555556  8.21250
std     0.726483  0.77171
min    19.000000  6.70000
25%    19.000000  7.87500
50%    19.000000  8.25000
75%    20.000000  8.82500
max    21.000000  9.10000

Task 4- check the 4th index observation with 'loc' slicing operator.

In [10]:
df.loc[4]

name         e
age       21.0
gender       m
branch     NaN
cgpa       8.2
Name: 4, dtype: object

Task 5 - Check the null values in your 'df'

In [13]:
df.isnull().any()

name      False
age        True
gender    False
branch     True
cgpa       True
dtype: bool